Repository aneoconsulting/ArmoniK.Admin.GUI, pull requests merged in 2022-11, with the labels that each got.

#273 feat: add favorites
  apps/app/src/app/core/core.module.ts
  apps/app/src/app/core/services/favorites.service.ts
  apps/app/src/app/core/services/index.ts
  apps/app/src/app/pages/pages.component.html
  apps/app/src/app/pages/pages.component.scss
  apps/app/src/app/pages/pages.component.spec.ts
  apps/app/src/app/pages/pages.component.ts
  apps/app/src/app/pages/pages.module.ts
  apps/app/src/app/pages/pages/components/index.ts
  apps/app/src/app/pages/pages/components/modal-favorites/modal-favorites.component.html
  apps/app/src/app/pages/pages/components/modal-favorites/modal-favorites.component.scss
  apps/app/src/app/pages/pages/components/modal-favorites/modal-favorites.component.ts
  apps/app/src/app/pages/pages/components/navigation-favorites/navigation-favorites.component.html
  apps/app/src/app/pages/pages/components/navigation-favorites/navigation-favorites.component.scss
  apps/app/src/app/pages/pages/components/navigation-favorites/navigation-favorites.component.ts
  apps/app/src/app/shared/shared-module.ts
  apps/app/src/assets/i18n/en.json
  apps/app/src/assets/i18n/fr.json
Labels: enhancement

#285 docs: fix typo in readme
  README.md
Labels: documentation

#272 feat: add history
  apps/app/src/app/core/core.module.ts
  apps/app/src/app/core/services/history.service.ts
  apps/app/src/app/core/services/index.ts
  apps/app/src/app/pages/components/index.ts
  apps/app/src/app/pages/components/navigation-history/navigation-history.component.html
  apps/app/src/app/pages/components/navigation-history/navigation-history.component.scss
  apps/app/src/app/pages/components/navigation-history/navigation-history.component.ts
  apps/app/src/app/pages/pages.component.html
  apps/app/src/app/pages/pages.component.spec.ts
  apps/app/src/app/pages/pages.component.ts
  apps/app/src/app/pages/pages.module.ts
  apps/app/src/assets/i18n/en.json
  apps/app/src/assets/i18n/fr.json
Labels: enhancement

#276 feat: add icons before nav items
  apps/app/src/app/core/types/app-nav-link.ts
  apps/app/src/app/pages/pages.component.html
  apps/app/src/app/pages/pages.component.spec.ts
  apps/app/src/app/pages/pages.component.ts
  apps/app/src/app/pages/pages.module.ts
Labels: enhancement

#297 fix: mongodb connexion
  README.md
  apps/api/src/app/common/options/mongo-client.options.ts
Labels: bug

#302 fix: translation on list sessions page
  apps/app/src/app/pages/pages/sessions-list/sessions-list.component.html
  apps/app/src/app/pages/pages/sessions-list/sessions-list.component.ts
Labels: bug

#301 feat: handle timeout in sessions
  apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
  apps/app/src/app/pages/pages/sessions-list/sessions-list.component.ts
Labels: enhancement

#298 refactor: use observables for seq and grafana settings
  apps/app/src/app/app.component.ts
  apps/app/src/app/core/services/settings.service.ts
  apps/app/src/app/pages/pages.component.html
  apps/app/src/app/pages/pages.component.spec.ts
  apps/app/src/app/pages/pages.component.ts
  apps/app/src/app/pages/pages/dashboard/components/applications-errors-list/applications-errors-list.component.ts
  apps/app/src/app/pages/pages/dashboard/dashboard.component.html
  apps/app/src/app/pages/pages/dashboard/dashboard.component.ts
  apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.ts
  apps/app/src/app/pages/pages/sessions/pages/session-detail/session-detail.component.html
  apps/app/src/app/pages/pages/sessions/pages/session-detail/session-detail.component.ts
Labels: enhancement

#286 feat: fetch tasks using grpc
  .yarn/install-state.gz
  apps/app/proxy.conf.json.example
  apps/app/src/app/core/core.module.ts
  apps/app/src/app/core/services/grpc/base-grpc.service.ts
  apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
  apps/app/src/app/core/services/grpc/grpc-tasks.service.ts
  apps/app/src/app/core/services/grpc/index.ts
  apps/app/src/app/core/services/index.ts
  apps/app/src/app/pages/pages/tasks-list/tasks-list.component.html
  apps/app/src/app/pages/pages/tasks-list/tasks-list.component.scss
  apps/app/src/app/pages/pages/tasks-list/tasks-list.component.ts
  apps/app/src/assets/i18n/en.json
  apps/app/src/assets/i18n/fr.json
  apps/app/src/colors.scss
Labels: enhancement

#308 refactor: browser title service
  apps/app/src/app/core/core.module.ts
  apps/app/src/app/core/services/browser-title.service.spec.ts
  apps/app/src/app/core/services/browser-title.service.ts
  apps/app/src/app/pages/pages/dashboard/dashboard.component.spec.ts
  apps/app/src/app/pages/pages/sessions/pages/session-detail/session-detail.component.spec.ts
Labels: enhancement

#310 refactor: auto refresh dropdown
  apps/app/src/app/pages/pages/sessions-list/sessions-list.component.html
  apps/app/src/app/pages/pages/sessions-list/sessions-list.component.ts
  apps/app/src/app/shared/components/auto-refresh-dropdown/auto-refresh-dropdown.component.html
  apps/app/src/app/shared/components/auto-refresh-dropdown/auto-refresh-dropdown.component.scss
  apps/app/src/app/shared/components/auto-refresh-dropdown/auto-refresh-dropdown.component.spec.ts
  apps/app/src/app/shared/components/auto-refresh-dropdown/auto-refresh-dropdown.component.ts
  apps/app/src/app/shared/components/index.ts
  apps/app/src/app/shared/shared-module.ts
  apps/app/src/assets/i18n/en.json
  apps/app/src/assets/i18n/fr.json
Labels: enhancement

#315 ci: install modules in CD
  .github/workflows/cd-docker.yml
Labels: bug

#287 feat: fetch results using grpc
  apps/app/src/app/core/core.module.ts
  apps/app/src/app/core/services/grpc/grpc-results.service.ts
  apps/app/src/app/core/services/grpc/index.ts
  apps/app/src/app/pages/pages-routing.module.ts
  apps/app/src/app/pages/pages.component.ts
  apps/app/src/app/pages/pages/results-list/results-list-routing.module.ts
  apps/app/src/app/pages/pages/results-list/results-list.component.html
  apps/app/src/app/pages/pages/results-list/results-list.component.scss
  apps/app/src/app/pages/pages/results-list/results-list.component.ts
  apps/app/src/app/pages/pages/results-list/results-list.module.ts
  apps/app/src/assets/i18n/en.json
  apps/app/src/assets/i18n/fr.json
  apps/app/src/colors.scss
Labels: enhancement

#311 refactor: modal favorites
  apps/app/src/app/pages/pages.module.ts
  apps/app/src/app/pages/pages/components/index.ts
  apps/app/src/app/pages/pages/components/modal-favorites/modal-favorites.component.html
  apps/app/src/app/shared/components/index.ts
  apps/app/src/app/shared/components/modal-favorites/index.ts
  apps/app/src/app/shared/components/modal-favorites/modal-favorites.component.html
  apps/app/src/app/shared/components/modal-favorites/modal-favorites.component.scss
  apps/app/src/app/shared/components/modal-favorites/modal-favorites.component.spec.ts
  apps/app/src/app/shared/components/modal-favorites/modal-favorites.component.ts
  apps/app/src/app/shared/shared-module.ts
  apps/app/src/assets/i18n/en.json
  apps/app/src/assets/i18n/fr.json
Labels: enhancement

#306 refactor: favorites service
  apps/app/src/app/core/services/favorites.service.spec.ts
  apps/app/src/app/core/services/favorites.service.ts
Labels: enhancement

#307 refactor: history service
  apps/app/src/app/core/services/history.service.spec.ts
  apps/app/src/app/core/services/history.service.ts
Labels: enhancement
